name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync upstream to fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/2ai-lab/courses
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
